name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4

      - name: Publish to JSR
        run: npx jsr publish

      - name: Get previous tag
        id: prev_tag
        run: echo "tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=2 | tail -n1))" >> $GITHUB_ENV

      - name: Get current tag
        id: current_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Release v${{ github.ref }}
          artifacts: "release.tar.gz"
          # body: Changelog https://github.com/P1N2O/utils/compare/${{ env.prev_tag }}...${{ env.tag }}
          generateReleaseNotes: true

        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        # with:
        #   tag_name: ${{ github.ref }}
        #   release_name: Release v${{ github.ref }}
        #   body: "Changelog: https://github.com/P1N2O/utils/compare/${{ env.prev_tag }}...${{ env.tag }}"
        #   draft: false
        #   prerelease: false
